### ISSUE TITLE
unable to install mconf-web bundle in torquebox

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#214]
---

Author Name: **Anonymous** (Anonymous)
Original Redmine Issue: 218, http://dev.mconf.org/redmine/issues/218

---

@Google user: kirantpa...@gmail.com@

Steps to Reproduce:
-------------------
1. Install torquebox 
   "http://repository-torquebox.forge.cloudbees.com/release/org/torquebox/torquebox-dist/1.0.0.CR1/torquebox-dist-1.0.0.CR1-bin.zip" rel="nofollow":http://repository-torquebox.forge.cloudbees.com/release/org/torquebox/torquebox-dist/1.0.0.CR1/torquebox-dist-1.0.0.CR1-bin.zip 
2. git clone the mconf-web in torquebox ("https://github.com/mconf/mconf-web" rel="nofollow":https://github.com/mconf/mconf-web )
3. make changes as per README.rdoc
4. go to mconf-web directory
5. [root@localhost mconf-web]# jruby -S bundle install 

Expected Output:
----------------
All gems should install without problem.

Actual Output:
--------------
[root@localhost mconf-web]# jruby -S bundle install
Fetching source index for "http://rubygems.org/" rel="nofollow":http://rubygems.org/ 
Using rake (0.8.7) 
Using abstract (1.0.0) 
Using action_mailer_tls (1.1.3) 
Using activesupport (3.0.3) 
Using builder (2.1.2) 
Using i18n (0.5.0) 
Using activemodel (3.0.3) 
Using erubis (2.6.6) 
Using rack (1.2.1) 
Using rack-mount (0.6.13) 
Using rack-test (0.5.7) 
Using tzinfo (0.3.24) 
Using actionpack (3.0.3) 
Using mime-types (1.16) 
Using polyglot (0.3.1) 
Using treetop (1.4.9) 
Using mail (2.2.15) 
Using actionmailer (3.0.3) 
Using arel (2.0.9) 
Using activerecord (3.0.3) 
Using activeresource (3.0.3) 
Using archive-tar-minitar (0.5.2) 
Using atom-tools (2.0.5) 
Using bigbluebutton-api-ruby (0.0.4) 
Using bundler (1.0.12) 
Using highline (1.6.1) 
Using net-ssh (2.1.3) 
Using net-scp (1.0.4) 
Using net-sftp (2.0.5) 
Using net-ssh-gateway (1.0.1) 
Using capistrano (2.5.19) 
Using chronic (0.3.0) 
Using ci_reporter (1.6.4) 
Using color (1.4.1) 
Using columnize (0.3.2) 
Using crack (0.1.8) 
Using daemons (1.0.10) 
Using diff-lcs (1.1.2) 
Using dynamic_form (1.1.3) 
Using exception_notification_rails3 (1.2.0) 
Using factory_girl (1.3.3) 
Using fckeditor (0.1.0) 
Using hpricot (0.8.4) 
Using simple-rss (1.2.3) 
Using feed-normalizer (1.5.2) 
Using ffaker (1.4.0) 
Using rspec-core (2.5.1) 
Using rspec-expectations (2.5.0) 
Using rspec-mocks (2.5.0) 
Using rspec (2.5.0) 
Using rspec-instafail (0.1.7) 
Using ruby-progressbar (0.0.9) 
Using fuubar (0.0.3) 
Using garb (0.9.1) 
Using gem_plugin (0.2.3) 
Using hoe (2.9.1) 
Using httparty (0.7.4) 
Using ruby_core_source (0.1.4) 
Installing linecache19 (0.5.11) with native extensions Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/bin/jruby extconf.rb --with-ruby-include=$rvm_path/src/$rvm_ruby_string/
WARNING: JRuby does not support native extensions or the `mkmf' library very well.
Check "http://kenai.com/projects/jruby/pages/Home" rel="nofollow":http://kenai.com/projects/jruby/pages/Home  for alternatives.
LoadError: no such file to load -- ruby_core_source
  require at org/jruby/RubyKernel.java:1038
   (root) at extconf.rb:2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/kiran/torque2/torquebox-1.0.0.CR1/jruby/bin/jruby

Gem files will remain installed in /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/lib/ruby/gems/1.8/gems/linecache19-0.5.11 for inspection.
Results logged to /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/lib/ruby/gems/1.8/gems/linecache19-0.5.11/ext/trace_nums/gem_make.out

  build_extensions at /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/lib/ruby/site_ruby/1.8/rubygems/installer.rb:529
              each at org/jruby/RubyArray.java:1602
  build_extensions at /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/lib/ruby/site_ruby/1.8/rubygems/installer.rb:482
           install at /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/lib/ruby/site_ruby/1.8/rubygems/installer.rb:156
           install at /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/source.rb:96
               run at /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/installer.rb:55
              each at /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/spec_set.rb:12
              each at org/jruby/RubyArray.java:1602
              each at /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/spec_set.rb:12
               run at /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/installer.rb:44
           install at /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/installer.rb:8
           install at /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/cli.rb:225
              send at org/jruby/RubyKernel.java:2052
               run at /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/vendor/thor/task.rb:21
       invoke_task at /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/vendor/thor/invocation.rb:118
          dispatch at /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/vendor/thor.rb:246
             start at /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/lib/ruby/gems/1.8/gems/bundler-1.0.12/lib/bundler/vendor/thor/base.rb:389
            (root) at /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/lib/ruby/gems/1.8/gems/bundler-1.0.12/bin/bundle:13
              load at org/jruby/RubyKernel.java:1063
            (root) at /home/kiran/torque2/torquebox-1.0.0.CR1/jruby/bin/bundle:19

Product information:
-------------------
1. torquebox-1.0.0.CR1
2. mconf-web master branch
3. [root@localhost mconf-web]# uname -a
Linux localhost.localdomain 2.6.32.21-168.fc12.x86_64 #1 SMP Wed Sep 15 16:12:07 UTC 2010 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Anonymous** (Anonymous)
Original Date: 2011-04-28T03:00:00Z

---

@Google user: kirantpa...@gmail.com@

got reply from torquebox team.

This error has nothing to do with TorqueBox specifically - I can't get the
linecache19 gem to install at all under plain old JRuby 1.6.1. The fact that it
uses native extensions is a good sign it probably wouldn't work correctly under
JRuby even if it could install.

Your best bet is to try and find a gem with replacement functionality that works
under JRuby and modify mconf-web to rely on that gem instead.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2011-04-28T03:00:00Z

---

@Google user: leonardo...@gmail.com@

Try removing ruby-debug19 from the Gemfile.
Clear your gems and "bundle install" again.

ruby-debug19 and linecache19 are only needed for debugging purposes.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2011-04-28T03:00:00Z

---

@Google user: leonardo...@gmail.com@

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Anonymous** (Anonymous)
Original Date: 2011-06-19T03:00:00Z

---

@Google user: michael....@gmail.com@

Hi, I'm also having the same issue.  I followed your instructions and removed ruby-debug19 from the Gemfile, but now I'm receiving the following output:


ubuntu@localhost:~/mconf-web$ bundle install
Fetching source index for "http://rubygems.org/" rel="nofollow":http://rubygems.org/ 
Using rake (0.8.7) 
Using abstract (1.0.0) 
Using action_mailer_tls (1.1.3) 
Using activesupport (3.0.8) 
Using builder (2.1.2) 
Using i18n (0.5.0) 
Using activemodel (3.0.8) 
Using erubis (2.6.6) 
Using rack (1.2.3) 
Using rack-mount (0.6.14) 
Using rack-test (0.5.7) 
Using tzinfo (0.3.27) 
Using actionpack (3.0.8) 
Using mime-types (1.16) 
Using polyglot (0.3.1) 
Using treetop (1.4.9) 
Using mail (2.2.19) 
Using actionmailer (3.0.8) 
Using arel (2.0.10) 
Using activerecord (3.0.8) 
Using activeresource (3.0.8) 
Using atom-tools (2.0.5) 
Using xml-simple (1.0.16) 
Using aws-s3 (0.6.2) 
Using attachment_fu (1.0.0) from git://github.com/mconf/attachment_fu.git (at master) 
Using nokogiri (1.4.1) 
Using bigbluebutton-api-ruby (0.0.10) 
Using bundler (1.0.15) 
Using thor (0.14.6) 
Using railties (3.0.8) 
Using rails (3.0.8) 
Using bigbluebutton_rails (0.0.4) from git://github.com/mconf/bigbluebutton_rails.git (at master) 
Using highline (1.6.2) 
Using net-ssh (2.1.4) 
Using net-scp (1.0.4) 
Using net-sftp (2.0.5) 
Using net-ssh-gateway (1.1.0) 
Using capistrano (2.6.0) 
Using capistrano-ext (1.2.1) 
Using chronic (0.3.0) 
Using ci_reporter (1.6.4) 
Using color (1.4.1) 
Using yamler (0.1.0) 
Using configatron (2.8.0) 
Using crack (0.1.8) 
Using diff-lcs (1.1.2) 
Using dynamic_form (1.1.4) 
Using exception_notification_rails3 (1.2.0) 
Using factory_girl (1.3.3) 
Using fckeditor (0.1.0) 
Using hpricot (0.8.4) 
Using simple-rss (1.2.3) 
Using feed-normalizer (1.5.2) 
Using ffaker (1.8.0) 
Using rspec-core (2.6.3) 
Using rspec-expectations (2.6.0) 
Using rspec-mocks (2.6.0) 
Using rspec (2.6.0) 
Using rspec-instafail (0.1.7) 
Using ruby-progressbar (0.0.10) 
Using fuubar (0.0.5) 
Using garb (0.9.1) 
Using hoe (2.9.4) 
Using htmlentities (4.3.0) 
Using httparty (0.7.7) 
Using jquery-rails (1.0.9) 
Installing mysql2 (0.2.7) with native extensions /home/ubuntu/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:533:in `rescue in block in build_extensions': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

        /home/ubuntu/.rvm/rubies/ruby-1.9.2-p180/bin/ruby extconf.rb 
checking for rb_thread_blocking_region()... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lm... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lz... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lsocket... no
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lnsl... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lmygcc... no
checking for mysql_query() in -lmysqlclient... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/ubuntu/.rvm/rubies/ruby-1.9.2-p180/bin/ruby
	--with-mysql-config
	--without-mysql-config
	--with-mysql-dir
	--without-mysql-dir
	--with-mysql-include
	--without-mysql-include=${mysql-dir}/include
	--with-mysql-lib
	--without-mysql-lib=${mysql-dir}/lib
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-mlib
	--without-mlib
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-zlib
	--without-zlib
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-socketlib
	--without-socketlib
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-nsllib
	--without-nsllib
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-mygcclib
	--without-mygcclib
	--with-mysqlclientlib
	--without-mysqlclientlib


Gem files will remain installed in /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/mysql2-0.2.7 for inspection.
Results logged to /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/mysql2-0.2.7/ext/mysql2/gem_make.out
	from /home/ubuntu/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:511:in `block in build_extensions'
	from /home/ubuntu/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:486:in `each'
	from /home/ubuntu/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:486:in `build_extensions'
	from /home/ubuntu/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:159:in `install'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/bundler-1.0.15/lib/bundler/source.rb:101:in `block in install'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/bundler-1.0.15/lib/bundler/rubygems_integration.rb:78:in `preserve_paths'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/bundler-1.0.15/lib/bundler/source.rb:91:in `install'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/bundler-1.0.15/lib/bundler/installer.rb:58:in `block (2 levels) in run'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/bundler-1.0.15/lib/bundler/rubygems_integration.rb:93:in `with_build_args'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/bundler-1.0.15/lib/bundler/installer.rb:57:in `block in run'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/bundler-1.0.15/lib/bundler/spec_set.rb:12:in `block in each'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/bundler-1.0.15/lib/bundler/spec_set.rb:12:in `each'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/bundler-1.0.15/lib/bundler/spec_set.rb:12:in `each'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/bundler-1.0.15/lib/bundler/installer.rb:49:in `run'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/bundler-1.0.15/lib/bundler/installer.rb:8:in `install'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/bundler-1.0.15/lib/bundler/cli.rb:222:in `install'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/bundler-1.0.15/lib/bundler/vendor/thor/task.rb:22:in `run'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/bundler-1.0.15/lib/bundler/vendor/thor/invocation.rb:118:in `invoke_task'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/bundler-1.0.15/lib/bundler/vendor/thor.rb:246:in `dispatch'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/bundler-1.0.15/lib/bundler/vendor/thor/base.rb:389:in `start'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/gems/bundler-1.0.15/bin/bundle:13:in `<top (required)>'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/bin/bundle:19:in `load'
	from /home/ubuntu/.rvm/gems/ruby-1.9.2-p180@mconf/bin/bundle:19:in `<main>'

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2011-06-22T03:00:00Z

---

@Google user: leonardo...@gmail.com@

Seems like you don't have the packages require by mysql.

Take a look at the file "script/setup", that is used to install the basic packages. Currently, mysql is being installed only when you run "script/setup production". For development only sqlite3 is installed. Maybe we'll have to change that.

In Ubuntu you would need to:
    apt-get install libmysqlclient15-dev mysql-server

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2011-09-05T03:00:00Z

---

@Google user: leonardo...@gmail.com@

This is an old issue and several things were improved in the installation of Mconf-Web.

If you're still having problems trying to install Mconf-Web in Torquebox, please open a new issue with information about it.
