### ISSUE TITLE
Unable to install mconf-web bundle

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#273]
---

Author Name: **Anonymous** (Anonymous)
Original Redmine Issue: 277, http://dev.mconf.org/redmine/issues/277

---

@Google user: michael....@gmail.com@

When I attempt to setup the database, I receive the following error message:

michael@ubuntu:~/mconf-web$ rake setup:db
(in /home/michael/mconf-web)

Running setup for the environment: development

* Running the task: db:drop
* Running the task: db:create
db/test.sqlite3 already exists
db/test.sqlite3 already exists
db/development.sqlite3 already exists
* Running the task: db:migrate
rake aborted!
SQLite3::SQLException: no such table: bigbluebutton_servers: SELECT  "bigbluebutton_servers".* FROM "bigbluebutton_servers" LIMIT 1

(See full trace by running task with --trace)

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2011-06-29T03:00:00Z

---

@Google user: leonardo...@gmail.com@

I got some questions:

- Which branch are you using and what is the last commit in your repository? You can paste the output of:
  * git log -1 --pretty=oneline
  * git branch

- Did you run "rake setup:basic" and edited the configuration files?

- Can you run "rake setup:db" it with "--trace" and post the output?

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2011-06-29T03:00:00Z

---

@Google user: leonardo...@gmail.com@

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Anonymous** (Anonymous)
Original Date: 2011-07-01T03:00:00Z

---

@Google user: kkepp...@gmail.com@

I'm having the same issues.
I'm on the stable branch, last commit is 5743bd18800796ad35d1fe3890616840e4e1638b

rake setup:basic is done, and rake setup:db --trace returns :

** Invoke setup:db (first_time)
** Execute setup:db

Running setup for the environment: development

* Running the task: db:drop
** Invoke db:drop (first_time)
** Invoke db:load_config (first_time)
** Invoke rails_env (first_time)
** Execute rails_env
** Execute db:load_config
** Execute db:drop
* Running the task: db:create
** Invoke db:create (first_time)
** Invoke db:load_config 
** Execute db:create
mconf_test already exists
* Running the task: db:migrate
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Mysql2::Error: Table 'mconf_dev.bigbluebutton_servers' doesn't exist: SELECT  `bigbluebutton_servers`.* FROM `bigbluebutton_servers` LIMIT 1
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activerecord-3.0.9/lib/active_record/connection_adapters/abstract_adapter.rb:207:in `rescue in log'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activerecord-3.0.9/lib/active_record/connection_adapters/abstract_adapter.rb:199:in `log'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/mysql2-0.2.7/lib/active_record/connection_adapters/mysql2_adapter.rb:314:in `execute'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/mysql2-0.2.7/lib/active_record/connection_adapters/mysql2_adapter.rb:635:in `select'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activerecord-3.0.9/lib/active_record/connection_adapters/abstract/database_statements.rb:7:in `select_all'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activerecord-3.0.9/lib/active_record/connection_adapters/abstract/query_cache.rb:56:in `select_all'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activerecord-3.0.9/lib/active_record/base.rb:473:in `find_by_sql'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activerecord-3.0.9/lib/active_record/relation.rb:64:in `to_a'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activerecord-3.0.9/lib/active_record/relation/finder_methods.rb:341:in `find_first'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activerecord-3.0.9/lib/active_record/relation/finder_methods.rb:122:in `first'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activerecord-3.0.9/lib/active_record/base.rb:444:in `first'
/home/kristof/mconf-web/config/routes.rb:7:in `block in <top (required)>'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/actionpack-3.0.9/lib/action_dispatch/routing/route_set.rb:233:in `instance_exec'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/actionpack-3.0.9/lib/action_dispatch/routing/route_set.rb:233:in `draw'
/home/kristof/mconf-web/config/routes.rb:1:in `<top (required)>'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:235:in `load'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:235:in `block in load'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `block in load_dependency'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:596:in `new_constants_in'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `load_dependency'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:235:in `load'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/railties-3.0.9/lib/rails/application.rb:127:in `block in reload_routes!'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/railties-3.0.9/lib/rails/application.rb:127:in `each'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/railties-3.0.9/lib/rails/application.rb:127:in `reload_routes!'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/railties-3.0.9/lib/rails/application.rb:120:in `block in routes_reloader'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activesupport-3.0.9/lib/active_support/file_update_checker.rb:32:in `call'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activesupport-3.0.9/lib/active_support/file_update_checker.rb:32:in `execute_if_updated'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/railties-3.0.9/lib/rails/application/finisher.rb:51:in `block (2 levels) in <module:Finisher>'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/railties-3.0.9/lib/rails/application/finisher.rb:52:in `call'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/railties-3.0.9/lib/rails/application/finisher.rb:52:in `block in <module:Finisher>'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/railties-3.0.9/lib/rails/initializable.rb:25:in `instance_exec'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/railties-3.0.9/lib/rails/initializable.rb:25:in `run'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/railties-3.0.9/lib/rails/initializable.rb:50:in `block in run_initializers'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/railties-3.0.9/lib/rails/initializable.rb:49:in `each'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/railties-3.0.9/lib/rails/initializable.rb:49:in `run_initializers'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/railties-3.0.9/lib/rails/application.rb:134:in `initialize!'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/railties-3.0.9/lib/rails/application.rb:77:in `method_missing'
/home/kristof/mconf-web/config/environment.rb:5:in `<top (required)>'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `require'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `block in require'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `block in load_dependency'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:596:in `new_constants_in'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `load_dependency'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `require'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/railties-3.0.9/lib/rails/application.rb:103:in `require_environment!'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@mconf/gems/railties-3.0.9/lib/rails/application.rb:218:in `block in initialize_tasks'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:636:in `block in execute'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:597:in `block in invoke_with_call_chain'
/home/kristof/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:607:in `block in invoke_prerequisites'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:604:in `each'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:604:in `invoke_prerequisites'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:596:in `block in invoke_with_call_chain'
/home/kristof/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/home/kristof/mconf-web/lib/tasks/setup.rake:51:in `block in run_tasks'
/home/kristof/mconf-web/lib/tasks/setup.rake:49:in `each'
/home/kristof/mconf-web/lib/tasks/setup.rake:49:in `run_tasks'
/home/kristof/mconf-web/lib/tasks/setup.rake:41:in `block (2 levels) in <top (required)>'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:636:in `block in execute'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:597:in `block in invoke_with_call_chain'
/home/kristof/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:2029:in `block (2 levels) in top_level'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:2029:in `block in top_level'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:2001:in `block in run'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/bin/rake:31:in `<top (required)>'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/bin/rake:19:in `load'
/home/kristof/.rvm/gems/ruby-1.9.2-p180@global/bin/rake:19:in `<main>'

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2011-07-01T03:00:00Z

---

@Google user: leonardo...@gmail.com@

There was an error in config/routes.rb that was fixed at: "https://github.com/mconf/mconf-web/commit/703ab5ae4d1f40471ebd0648846f53348678fa88" rel="nofollow":https://github.com/mconf/mconf-web/commit/703ab5ae4d1f40471ebd0648846f53348678fa88 

Still a temporary implementation, but it is working now. Just update your repository and try again.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2011-09-05T03:00:00Z

---

@Google user: leonardo...@gmail.com@

This is an old issue that was already fixed (see last comment).
If you're still having this issue, please reopen the ticket.
