### ISSUE TITLE
errors#error_404 (ActionView::MissingTemplate)  "Missing template errors/error_500 with {:locale=>[...

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#552]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1105, http://dev.mconf.org/redmine/issues/1105
Original Date: 2014-11-04
Original Assignee: Fernando Bottin

---

Error reported by @exception_notifier@:

```
A ActionView::MissingTemplate occurred in errors#error_404:

  Missing template errors/error_500 with {:locale=>[:"pt-br", :en], :formats=>[:css], :handlers=>[:erb, :builder, :haml, :rabl]}. Searched in:
  * "/var/www/mconf-web/releases/20131202161519/app/views"
  * "/var/www/mconf-web/shared/bundle/ruby/1.9.1/gems/twitter-bootstrap-rails-2.2.7/app/views"
  * "/var/www/mconf-web/shared/bundle/ruby/1.9.1/bundler/gems/bigbluebutton_rails-41a8388a451a/app/views"
  * "/var/www/mconf-web/shared/bundle/ruby/1.9.1/gems/devise-2.2.4/app/views"

  actionpack (3.2.11) lib/action_view/path_set.rb:58:in `find'


-------------------------------
Request:
-------------------------------

  * URL       : https://200.130.35.223/admin/common/ie.css
  * IP address: 86.105.36.246
  * Parameters: {"controller"=>"errors", "action"=>"error_404", "not_found"=>"admin/common/ie", "format"=>"css"}
  * Rails root: /var/www/mconf-web/releases/20131202161519
  * Timestamp : 2013-12-13 00:57:12 -0200

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {}

-------------------------------
Environment:
-------------------------------

  * DOCUMENT_ROOT                                  : /var/www/mconf-web/current/public
  * HTTPS                                          : on
  * HTTP_ACCEPT                                    : */*
  * HTTP_HOST                                      : 200.130.35.223
  * ORIGINAL_FULLPATH                              : /admin/common/ie.css
  * PASSENGER_APP_GROUP_NAME                       : /var/www/mconf-web/current
  * PASSENGER_APP_ROOT                             : /var/www/mconf-web/current
  * PASSENGER_APP_TYPE                             : rack
  * PASSENGER_CONNECT_PASSWORD                     : [FILTERED]
  * PASSENGER_DEBUGGER                             : false
  * PASSENGER_ENV                                  : production
  * PASSENGER_FRIENDLY_ERROR_PAGES                 : true
  * PASSENGER_GROUP                                :
  * PASSENGER_MAX_PRELOADER_IDLE_TIME              : -1
  * PASSENGER_MAX_REQUESTS                         : 0
  * PASSENGER_MIN_INSTANCES                        : 1
  * PASSENGER_RESTART_DIR                          :
  * PASSENGER_RUBY                                 : /home/mconf/.rbenv/versions/1.9.3-p194/bin/ruby
  * PASSENGER_SHOW_VERSION_IN_HEADER               : true
  * PASSENGER_SPAWN_METHOD                         : smart
  * PASSENGER_START_TIMEOUT                        : 90
  * PASSENGER_STATUS_LINE                          : false
  * PASSENGER_STAT_THROTTLE_RATE                   : 0
  * PASSENGER_USER                                 :
  * PATH_INFO                                      : /admin/common/ie.css
  * QUERY_STRING                                   :
  * REMOTE_ADDR                                    : 86.105.36.246
  * REMOTE_PORT                                    : 48756
  * REQUEST_METHOD                                 : GET
  * REQUEST_URI                                    : /admin/common/ie.css
  * SCRIPT_NAME                                    :
  * SCRIPT_URI                                     : https://200.130.35.223/admin/common/ie.css
  * SCRIPT_URL                                     : /admin/common/ie.css
  * SERVER_ADDR                                    : 200.130.35.223
  * SERVER_ADMIN                                   : [no address given]
  * SERVER_NAME                                    : 200.130.35.223
  * SERVER_PORT                                    : 443
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : Apache/2.2.22 (Ubuntu)
  * action_controller.instance                     : errors#error_404
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x00000004e363c8>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x007f758cc4ae88>
  * action_dispatch.logger                         : #<ActiveSupport::TaggedLogging:0x000000049c6f18>
  * action_dispatch.parameter_filter               : [:password, :password_confirmation, /RAW_POST_DATA/]
  * action_dispatch.remote_ip                      : 86.105.36.246
  * action_dispatch.request.content_type           :
  * action_dispatch.request.formats                : [text/css]
  * action_dispatch.request.parameters             : {"controller"=>"errors", "action"=>"error_404", "not_found"=>"admin/common/ie", "format"=>"css"}
  * action_dispatch.request.path_parameters        : {:controller=>"errors", :action=>"error_404", :not_found=>"admin/common/ie", :format=>"css"}
  * action_dispatch.request.query_parameters       : {}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {}
  * action_dispatch.request_id                     : e00de6cf661aaa105968bf4cb4f08206
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x00000002a5a350>
  * action_dispatch.secret_token                   : 0b22a987a3beb701c128a787cd2914351df06cfce413ca0e4034574e0f7d144692d940fe02374c39dbbbc898e9bda27356a89d14d5c4235f4979b4bea0072f0b
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * exception_notifier.options                     : {:sender_address=>"\"Mconf RNP\" <mconf-se@rnp.br>", :exception_recipients=>["support@mconf.org"], :email_prefix=>"[mconf2.rnp.br error] ", :sections=>["request", "session", "environment", "backtrace"], :background_sections=>["backtrace", "data"], :verbose_subject=>true, :normalize_subject=>false, :ignore_exceptions=>["ActiveRecord::RecordNotFound", "AbstractController::ActionNotFound", "ActionController::RoutingError"], :ignore_crawlers=>[], :ignore_if=>#<Proc:0x00000004c08f88@/var/www/mconf-web/shared/bundle/ruby/1.9.1/gems/exception_notification-2.6.1/lib/exception_notifier.rb:30 (lambda)>}
  * rack-cache.allow_reload                        : false
  * rack-cache.allow_revalidate                    : false
  * rack-cache.cache_key                           : Rack::Cache::Key
  * rack-cache.default_ttl                         : 0
  * rack-cache.entitystore                         : rails:/
  * rack-cache.ignore_headers                      : ["Set-Cookie"]
  * rack-cache.metastore                           : rails:/
  * rack-cache.private_headers                     : ["Authorization", "Cookie"]
  * rack-cache.storage                             : #<Rack::Cache::Storage:0x00000004ef4b98>
  * rack-cache.use_native_ttl                      : false
  * rack-cache.verbose                             : false
  * rack.errors                                    : #<IO:0x00000000d94310>
  * rack.hijack                                    : #<Proc:0x007f758cc43e58@/home/mconf/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/passenger-4.0.19/lib/phusion_passenger/rack/thread_handler_extension.rb:69 (lambda)>
  * rack.hijack?                                   : true
  * rack.input                                     : #<PhusionPassenger::Utils::TeeInput:0x007f758cc44560>
  * rack.multiprocess                              : true
  * rack.multithread                               : false
  * rack.request.cookie_hash                       : {}
  * rack.request.query_hash                        : {}
  * rack.request.query_string                      :
  * rack.run_once                                  : false
  * rack.session                                   : {}
  * rack.session.options                           : {:path=>"/", :domain=>nil, :expire_after=>nil, :secure=>false, :httponly=>true, :defer=>false, :renew=>false, :secret=>"e938979151a3d6bd2f926a17f7eca92ac05b36ddf779504a3a7787d65b3d", :coder=>#<Rack::Session::Cookie::Base64::Marshal:0x00000004c15d00>, :id=>nil}
  * rack.url_scheme                                : https
  * rack.version                                   : [1, 2]
  * warden                                         : Warden::Proxy:70071424799980 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:ldap_authenticatable, :rememberable, :database_authenticatable]}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x0000000633c880>}

  * Process: 23752
  * Server : gemini

-------------------------------
Backtrace:
-------------------------------

  actionpack (3.2.11) lib/action_view/path_set.rb:58:in `find'
  actionpack (3.2.11) lib/action_view/lookup_context.rb:109:in `find'
  actionpack (3.2.11) lib/action_view/renderer/abstract_renderer.rb:3:in `find_template'
  actionpack (3.2.11) lib/action_view/renderer/template_renderer.rb:34:in `determine_template'
  actionpack (3.2.11) lib/action_view/renderer/template_renderer.rb:10:in `render'
  actionpack (3.2.11) lib/action_view/renderer/renderer.rb:36:in `render_template'
  actionpack (3.2.11) lib/action_view/renderer/renderer.rb:17:in `render'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:110:in `_render_template'
  actionpack (3.2.11) lib/action_controller/metal/streaming.rb:225:in `_render_template'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:103:in `render_to_body'
  actionpack (3.2.11) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  actionpack (3.2.11) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:88:in `render'
  actionpack (3.2.11) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  activesupport (3.2.11) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
  /home/mconf/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
  activesupport (3.2.11) lib/active_support/core_ext/benchmark.rb:5:in `ms'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
  activerecord (3.2.11) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:39:in `render'
  app/controllers/application_controller.rb:214:in `render_500'
  activesupport (3.2.11) lib/active_support/rescuable.rb:80:in `call'
  activesupport (3.2.11) lib/active_support/rescuable.rb:80:in `rescue_with_handler'
  actionpack (3.2.11) lib/action_controller/metal/rescue.rb:15:in `rescue_with_handler'
  actionpack (3.2.11) lib/action_controller/metal/rescue.rb:32:in `rescue in process_action'
  actionpack (3.2.11) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.11) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.11) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.11) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.11) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.11) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.11) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.11) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.11) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.11) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:601:in `call'
  exception_notification (2.6.1) lib/exception_notifier.rb:34:in `call'
  galetahub-simple_captcha (0.1.3) lib/simple_captcha/middleware.rb:20:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.11) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.11) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in `_run__4214444018542805883__call__4362998550014534302__callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.11) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.11) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  rack (1.4.5) lib/rack/sendfile.rb:102:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.11) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.11) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.11) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.11) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.11) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.11) lib/rails/engine.rb:479:in `call'
  railties (3.2.11) lib/rails/application.rb:223:in `call'
  railties (3.2.11) lib/rails/railtie/configurable.rb:30:in `method_missing'
  passenger (4.0.19) lib/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  passenger (4.0.19) lib/phusion_passenger/request_handler/thread_handler.rb:140:in `accept_and_process_next_request'
  passenger (4.0.19) lib/phusion_passenger/request_handler/thread_handler.rb:108:in `main_loop'
  passenger (4.0.19) lib/phusion_passenger/request_handler.rb:441:in `block (3 levels) in start_threads'


```

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2014-10-22T13:15:52Z

---

Another action that triggered the error (the error that the close.png is not found was already fixed):

```
production.log.1-Started GET "/assets/jquery/noty/close-0840e18c302a84beb787687589c5db03.png" for 177.142.119.11 at 2014-10-21 15:34:45 -0200
production.log.1-Processing by ErrorsController#error_404 as PNG
production.log.1-  Parameters: {"not_found"=>"assets/jquery/noty/close-0840e18c302a84beb787687589c5db03"}
production.log.1-Completed 500 Internal Server Error in 8ms
production.log.1-
production.log.1-ActionView::MissingTemplate (Missing template errors/error_500 with {:locale=>[:"pt-br", :pt, :en], :formats=>[:png], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :haml, :rabl]}. Searched in:
production.log.1-  * "/var/www/mconf-web/releases/20141020164331/app/mailers/views"
production.log.1-  * "/var/www/mconf-web/releases/20141020164331/app/views"
production.log.1-  * "/var/www/mconf-web/shared/bundle/ruby/2.1.0/bundler/gems/mweb_events-769fa7fb451e/app/views"
production.log.1-  * "/var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/twitter-bootstrap-rails-2.2.8/app/views"
production.log.1-  * "/var/www/mconf-web/shared/bundle/ruby/2.1.0/bundler/gems/bigbluebutton_rails-f7201867c8c9/app/views"
production.log.1-  * "/var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/devise-3.2.4/app/views"
production.log.1-):
production.log.1-  app/controllers/application_controller.rb:197:in `render_error'
production.log.1-  app/controllers/application_controller.rb:208:in `render_500'

```
