### ISSUE TITLE
undefined method `error_handler' for WebConferenceMailer:Class

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#652]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1365, http://dev.mconf.org/redmine/issues/1365

Original Assignee: Lucas Zawacki

---

Happens when an exception is raised when sending/rendering an email. Happens in the other mailers too, not only on WebConferenceMailer.

A snippet of the errro seen on resque's admin interface:

```
Exception
    NoMethodError
Error
    undefined method `error_handler' for WebConferenceMailer:Class

    /home/daronco/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionmailer-4.1.4/lib/action_mailer/base.rb:553:in `method_missing'
    /home/daronco/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/resque_mailer-2.2.6/lib/resque_mailer.rb:42:in `method_missing'

```

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2014-10-10T15:18:08Z

---

The method to handle the error was inside BaseMailer, but for some reasons it was not working as it should. Rails and resque_mailer change the mailers in a way that calling @mailer.error_handler@ was not really calling the method. Tried to change the name of the method and move it around (public/private), but it didn't work. The solution was to move the handling method to a different class inside lib/ and now everything works fine.

Note for the future: mailers are weird and should have methods to send emails and nothing more.
