### ISSUE TITLE
(Mysql2::Error) "Duplicate entry '47' for key 'index_shib_tokens_on_user_id'"

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#667]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1397, http://dev.mconf.org/redmine/issues/1397
Original Date: 2014-10-27
Original Assignee: Lucas Zawacki

---

```
A Mysql2::Error occurred in background at 2014-10-27 14:30:24 -0200 :

  Duplicate entry '47' for key 'index_shib_tokens_on_user_id'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'

  -------------------------------
Backtrace:
-------------------------------

  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `execute'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/mysql2_adapter.rb:254:in `exec_delete'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:101:in `update'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `update'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/relation.rb:77:in `_update_record'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/persistence.rb:493:in `_update_record'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/locking/optimistic.rb:70:in `_update_record'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/attribute_methods/dirty.rb:83:in `_update_record'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/callbacks.rb:310:in `block in _update_record'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:82:in `run_callbacks'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/callbacks.rb:310:in `_update_record'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/timestamp.rb:70:in `_update_record'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/persistence.rb:482:in `create_or_update'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/callbacks.rb:302:in `block in create_or_update'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:113:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:113:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:86:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:86:in `run_callbacks'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/callbacks.rb:302:in `create_or_update'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/persistence.rb:125:in `save!'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/validations.rb:57:in `save!'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/transactions.rb:273:in `block in save!'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/transactions.rb:208:in `transaction'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/transactions.rb:273:in `save!'
  /var/www/mconf-web/releases/20141025143306/app/controllers/shibboleth_controller.rb:222:in `associate_with_existent_account'
  /var/www/mconf-web/releases/20141025143306/app/controllers/shibboleth_controller.rb:100:in `create_association'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/abstract_controller/base.rb:189:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/rendering.rb:10:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:113:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:113:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:149:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:149:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:149:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:149:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:229:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:229:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:86:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:86:in `run_callbacks'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:159:in `block in instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:159:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/abstract_controller/base.rb:136:in `process'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionview-4.1.4/lib/action_view/rendering.rb:30:in `process'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal.rb:196:in `dispatch'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal.rb:232:in `block in action'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:82:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:50:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/journey/router.rb:71:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/journey/router.rb:59:in `each'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/journey/router.rb:59:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:678:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/exception_notification-4.0.1/lib/exception_notification/rack.rb:28:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/simple_captcha2-0.3.2/lib/simple_captcha/middleware.rb:26:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:35:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/flash.rb:254:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/query_cache.rb:36:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:82:in `run_callbacks'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/railties-4.1.4/lib/rails/rack/logger.rb:38:in `call_app'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/railties-4.1.4/lib/rails/rack/logger.rb:20:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/tagged_logging.rb:26:in `tagged'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/tagged_logging.rb:68:in `tagged'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/railties-4.1.4/lib/rails/rack/logger.rb:20:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/railties-4.1.4/lib/rails/engine.rb:514:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/railties-4.1.4/lib/rails/application.rb:144:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/railties-4.1.4/lib/rails/railtie.rb:194:in `public_send'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/railties-4.1.4/lib/rails/railtie.rb:194:in `method_missing'
  /home/mconf/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/passenger-4.0.49/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /home/mconf/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/passenger-4.0.49/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /home/mconf/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/passenger-4.0.49/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /home/mconf/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/passenger-4.0.49/lib/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'

-------------------------------
Data:
-------------------------------

  * data: {}

```

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2015-03-25T15:51:43Z

---

See https://github.com/mconf/mconf-web/pull/69

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2015-07-07T20:05:24Z

---

Hasn't happened in production for the past ~3 months, so I'm assuming the fix worked.
