### ISSUE TITLE
(NoMethodError) "undefined method `logo' for #<Space:0x007f417f1cb8e0>"

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#679]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1414, http://dev.mconf.org/redmine/issues/1414

Original Assignee: Lucas Zawacki

---

Happens when trying to access the URL "/spaces.js".

```
A NoMethodError occurred in background at 2014-11-25 23:01:05 -0200 :

  undefined method `logo' for #<Space:0x007f417f1cb8e0>
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activemodel-4.1.4/lib/active_model/attribute_methods.rb:435:in `method_missing'

  -------------------------------
Backtrace:
-------------------------------

  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activemodel-4.1.4/lib/active_model/attribute_methods.rb:435:in `method_missing'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/attribute_methods.rb:208:in `method_missing'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activemodel-4.1.4/lib/active_model/serialization.rb:157:in `block in serializable_add_includes'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activemodel-4.1.4/lib/active_model/serialization.rb:156:in `each'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activemodel-4.1.4/lib/active_model/serialization.rb:156:in `serializable_add_includes'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activemodel-4.1.4/lib/active_model/serialization.rb:112:in `serializable_hash'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/serialization.rb:17:in `serializable_hash'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/orm/activerecord.rb:65:in `serializable_hash'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activemodel-4.1.4/lib/active_model/serializers/json.rb:99:in `as_json'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/core_ext/object/json.rb:140:in `block in as_json'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/core_ext/object/json.rb:140:in `map'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/core_ext/object/json.rb:140:in `as_json'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.4/lib/active_record/relation.rb:236:in `as_json'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/json/encoding.rb:34:in `encode'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/json/encoding.rb:21:in `encode'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
  /var/www/mconf-web/releases/20141025143306/app/controllers/spaces_controller.rb:63:in `block (2 levels) in index'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/responder.rb:236:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/responder.rb:236:in `default_render'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/responder.rb:172:in `to_js'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/responder.rb:158:in `respond'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/responder.rb:151:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/mime_responds.rb:400:in `respond_with'
  /var/www/mconf-web/releases/20141025143306/app/controllers/spaces_controller.rb:60:in `index'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/abstract_controller/base.rb:189:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/action_controller/metal/rendering.rb:10:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:113:in `call'

```

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2014-12-08T14:52:33Z

---

See https://github.com/mconf/mconf-web/pull/58
