### ISSUE TITLE
undefined method `id' for nil:NilClass on join_request_sender_worker.rb:26

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#761]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1730, http://dev.mconf.org/redmine/issues/1730

Original Assignee: Daniela Cavalheiro

---

The following error was seen in one production server:

    undefined method `id' for nil:NilClass
      /var/www/mconf-web/releases/20150609193502/app/workers/join_request_sender_worker.rb:26

This is the recent activity loaded by the worker:

    RecentActivity id: 5059, trackable_id: 666, trackable_type: "JoinRequest", owner_id: 444, owner_type: "Space", key: "join_request.request", parameters: {:candidate_id=>555, :username=>"Someone"}, recipient_id: nil, recipient_type: nil, created_at: "2015-05-21 21:48:27", updated_at: "2015-08-10 19:23:00", notified: true

The trackable associated with it doesn't exist.

The full trace:

```
A NoMethodError occurred in background at 2015-08-10 21:16:51 +0200 :

  undefined method `id' for nil:NilClass
  /var/www/mconf-web/releases/20150609193502/app/workers/join_request_sender_worker.rb:26:in `block in perform'

  -------------------------------
Backtrace:
-------------------------------

  /var/www/mconf-web/releases/20150609193502/app/workers/join_request_sender_worker.rb:26:in `block in perform'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/relation/delegation.rb:46:in `each'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/relation/delegation.rb:46:in `each'
  /var/www/mconf-web/releases/20150609193502/app/workers/join_request_sender_worker.rb:24:in `perform'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:227:in `perform'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
  /home/mconf/.rbenv/versions/2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/bin/rake:23:in `load'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/bin/rake:23:in `<main>'

-------------------------------
Data:
-------------------------------

  * data: {:resque=>
    {:failed_at=>"2015-08-10 16:16:51 -0300",
     :queue=>"join_requests",
     :worker=>"gemini:41715:*",
     :payload=>{"class"=>"JoinRequestSenderWorker", "args"=>[5059]},
     :error_class=>"NoMethodError",
     :error_message=>"undefined method `id' for nil:NilClass"}}

```

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Daniela Cavalheiro** (Daniela Cavalheiro)
Original Date: 2015-09-30T18:39:30Z

---

https://github.com/mconf/mconf-web/commit/5f91d29e8bae1a32881fd5b92d2c9e6c02c33f42

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2015-10-02T15:26:35Z

---

See https://github.com/mconf/mconf-web/pull/144
