### ISSUE TITLE
Error when creating events: (ArgumentError) "invalid date"

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#770]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1752, http://dev.mconf.org/redmine/issues/1752

Original Assignee: Lucas Zawacki

---

Stack trace:

```
(ArgumentError) "invalid date"
An ArgumentError occurred in background at 2015-08-26 11:58:44 +0200 :

  invalid date
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/bundler/gems/mweb_events-c2f02894b965/app/models/mweb_events/event.rb:223:in `parse'

  -------------------------------
Backtrace:
-------------------------------

  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/bundler/gems/mweb_events-c2f02894b965/app/models/mweb_events/event.rb:223:in `parse'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/bundler/gems/mweb_events-c2f02894b965/app/models/mweb_events/event.rb:223:in `concat_date_time'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:429:in `block in make_lambda'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:161:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:161:in `block in halting'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:501:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:501:in `block in call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:501:in `each'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:501:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:86:in `run_callbacks'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activemodel-4.1.11/lib/active_model/validations/callbacks.rb:111:in `run_validations!'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activemodel-4.1.11/lib/active_model/validations.rb:317:in `valid?'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/validations.rb:70:in `valid?'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/validations.rb:77:in `perform_validations'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/validations.rb:51:in `save'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/attribute_methods/dirty.rb:21:in `save'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:268:in `block (2 levels) in save'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:208:in `transaction'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:268:in `block in save'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/transactions.rb:267:in `save'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/bundler/gems/mweb_events-c2f02894b965/app/controllers/mweb_events/events_controller.rb:69:in `block in create'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/metal/mime_responds.rb:433:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/metal/mime_responds.rb:433:in `retrieve_collector_from_mimes'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/metal/mime_responds.rb:256:in `respond_to'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/bundler/gems/mweb_events-c2f02894b965/app/controllers/mweb_events/events_controller.rb:68:in `create'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/abstract_controller/base.rb:189:in `process_action'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/metal/rendering.rb:10:in `process_action'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:113:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:113:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:502:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:502:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:86:in `run_callbacks'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/notifications.rb:159:in `block in instrument'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/notifications.rb:159:in `instrument'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/abstract_controller/base.rb:136:in `process'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionview-4.1.11/lib/action_view/rendering.rb:30:in `process'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/metal.rb:196:in `dispatch'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/metal.rb:232:in `block in action'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:82:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:50:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/journey/router.rb:73:in `block in call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/journey/router.rb:59:in `each'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/journey/router.rb:59:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:692:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.11/lib/rails/engine.rb:514:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.11/lib/rails/railtie.rb:194:in `public_send'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.11/lib/rails/railtie.rb:194:in `method_missing'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/journey/router.rb:73:in `block in call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/journey/router.rb:59:in `each'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/journey/router.rb:59:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:692:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/exception_notification-4.0.1/lib/exception_notification/rack.rb:28:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/conditionalget.rb:35:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/flash.rb:254:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/cookies.rb:562:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/query_cache.rb:36:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:82:in `run_callbacks'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.11/lib/rails/rack/logger.rb:38:in `call_app'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.11/lib/rails/rack/logger.rb:20:in `block in call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/tagged_logging.rb:26:in `tagged'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/tagged_logging.rb:68:in `tagged'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.11/lib/rails/rack/logger.rb:20:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.11/lib/rails/engine.rb:514:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.11/lib/rails/application.rb:144:in `call'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.11/lib/rails/railtie.rb:194:in `public_send'
  /var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/railties-4.1.11/lib/rails/railtie.rb:194:in `method_missing'
  /home/mconf/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /home/mconf/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /home/mconf/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /home/mconf/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

-------------------------------
Data:
-------------------------------

  * data: {}

```

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2015-09-23T18:38:22Z

---

[Originally by Erik De Neve]


My production.log shows the following:

ESC[0;37m2015-08-26 12:59:58.161ESC[0m [ESC[32mINFO ESC[0m] Started GET "/events" for 193.190.130.1 at 2015-08-26 12:59:58 +0200 (pid:1643)
ESC[0;37m2015-08-26 12:59:58.163ESC[0m [ESC[32mINFO ESC[0m] Processing by MwebEvents::EventsController#index as HTML (pid:1643)
ESC[0;37m2015-08-26 12:59:58.200ESC[0m [ESC[32mINFO ESC[0m] Redirected to https://mconf.belnet.be/events?show=all (pid:1643)
ESC[0;37m2015-08-26 12:59:58.200ESC[0m [ESC[32mINFO ESC[0m] Completed 302 Found in 37ms (ActiveRecord: 2.4ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.364ESC[0m [ESC[32mINFO ESC[0m] Started GET "/events?show=all" for 193.190.130.1 at 2015-08-26 12:59:58 +0200 (pid:1643)
ESC[0;37m2015-08-26 12:59:58.365ESC[0m [ESC[32mINFO ESC[0m] Processing by MwebEvents::EventsController#index as HTML (pid:1643)
ESC[0;37m2015-08-26 12:59:58.365ESC[0m [ESC[32mINFO ESC[0m] Parameters: {"show"=>"all"} (pid:1643)
ESC[0;37m2015-08-26 12:59:58.386ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_page_title.html.haml (0.3ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.414ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_sidebar_content_block.html.haml (0.2ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.423ESC[0m [ESC[32mINFO ESC[0m] Rendered mweb_events/events/_unified_event.html.haml (2.9ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.426ESC[0m [ESC[32mINFO ESC[0m] Rendered mweb_events/events/_unified_event.html.haml (2.5ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.428ESC[0m [ESC[32mINFO ESC[0m] Rendered mweb_events/events/_unified_event.html.haml (2.4ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.433ESC[0m [ESC[32mINFO ESC[0m] Rendered mweb_events/events/_unified_event.html.haml (4.0ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.444ESC[0m [ESC[32mINFO ESC[0m] Rendered mweb_events/events/_unified_event.html.haml (3.5ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.448ESC[0m [ESC[32mINFO ESC[0m] Rendered mweb_events/events/_unified_event.html.haml (3.7ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.452ESC[0m [ESC[32mINFO ESC[0m] Rendered mweb_events/events/_unified_event.html.haml (3.7ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.452ESC[0m [ESC[32mINFO ESC[0m] Rendered mweb_events/events/_list_view.html.haml (32.8ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.452ESC[0m [ESC[32mINFO ESC[0m] Rendered mweb_events/events/index.html.haml within layouts/mweb_events/application (68.1ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.465ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_application_navbar.html.haml (9.1ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.468ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_footer.html.haml (3.2ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.469ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_analytics.html.haml (0.1ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.469ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_notifications.html.haml (0.1ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.471ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_chat.html.haml (1.7ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.471ESC[0m [ESC[32mINFO ESC[0m] Rendered shared/_copy_modal.html.haml (0.4ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.473ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_javascript_locales.html.haml (0.1ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.474ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/application.html.haml (21.1ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:58.474ESC[0m [ESC[32mINFO ESC[0m] Completed 200 OK in 109ms (Views: 87.9ms | ActiveRecord: 3.7ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:59.841ESC[0m [ESC[32mINFO ESC[0m] Started GET "/events/new" for 193.190.130.1 at 2015-08-26 12:59:59 +0200 (pid:1643)
ESC[0;37m2015-08-26 12:59:59.844ESC[0m [ESC[32mINFO ESC[0m] Processing by MwebEvents::EventsController#new as HTML (pid:1643)
ESC[0;37m2015-08-26 12:59:59.863ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_page_title.html.haml (0.3ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:59.907ESC[0m [ESC[32mINFO ESC[0m] Rendered vendor/bundle/ruby/2.2.0/bundler/gems/mweb_events-c2f02894b965/app/views/mweb_events/events/_markdown_en.html.haml (0.3ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:59.907ESC[0m [ESC[32mINFO ESC[0m] Rendered vendor/bundle/ruby/2.2.0/bundler/gems/mweb_events-c2f02894b965/app/views/mweb_events/events/_markdown_modal.html.haml (1.2ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:59.909ESC[0m [ESC[32mINFO ESC[0m] Rendered vendor/bundle/ruby/2.2.0/bundler/gems/mweb_events-c2f02894b965/app/views/mweb_events/events/_form.html.haml (45.5ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:59.911ESC[0m [ESC[32mINFO ESC[0m] Rendered mweb_events/events/new.html.haml within layouts/mweb_events/application (49.4ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:59.924ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_application_navbar.html.haml (9.2ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:59.928ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_footer.html.haml (3.3ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:59.928ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_analytics.html.haml (0.1ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:59.928ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_notifications.html.haml (0.1ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:59.930ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_chat.html.haml (1.8ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:59.931ESC[0m [ESC[32mINFO ESC[0m] Rendered shared/_copy_modal.html.haml (0.4ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:59.933ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_javascript_locales.html.haml (0.1ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:59.933ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/application.html.haml (21.5ms) (pid:1643)
ESC[0;37m2015-08-26 12:59:59.936ESC[0m [ESC[32mINFO ESC[0m] Completed 200 OK in 92ms (Views: 73.9ms | ActiveRecord: 1.5ms) (pid:1643)
ESC[0;37m2015-08-26 13:00:04.442ESC[0m [ESC[32mINFO ESC[0m] BigbluebuttonFinishMeetings worker running (pid:8178)
ESC[0;37m2015-08-26 13:00:09.294ESC[0m [ESC[32mINFO ESC[0m] Started POST "/events" for 193.190.130.1 at 2015-08-26 13:00:09 +0200 (pid:1643)
ESC[0;37m2015-08-26 13:00:09.297ESC[0m [ESC[32mINFO ESC[0m] Processing by MwebEvents::EventsController#create as HTML (pid:1643)
ESC[0;37m2015-08-26 13:00:09.297ESC[0m [ESC[32mINFO ESC[0m] Parameters: {"utf8"=>"✓", "authenticity_token"=>"QJCfykl4uTy0CRSEOCbHP7lLhMW5kBOGOOYEshuohNk=", "event"=>{"name"=>"erfdcd", "owner_id"=>"", "owner_type"=>"", "date_stored_format"=>"%m/%d/%Y %H:%M", "start_on_date"=>"08/26/2015", "start_on_time(1i)"=>"2015", "start_on_time(2i)"=>"8", "start_on_time(3i)"=>"26", "start_on_time(4i)"=>"00", "start_on_time(5i)"=>"00", "end_on_date"=>"08/27/2015", "end_on_time(1i)"=>"2015", "end_on_time(2i)"=>"8", "end_on_time(3i)"=>"26", "end_on_time(4i)"=>"00", "end_on_time(5i)"=>"00", "time_zone"=>"Brussels", "location"=>"", "address"=>"", "social_networks"=>[""], "summary"=>"", "description"=>""}, "commit"=>"Save"} (pid:1643)
ESC[0;37m2015-08-26 13:00:09.326ESC[0m [ESC[32mINFO ESC[0m] Rendered vendor/bundle/ruby/2.2.0/gems/exception_notification-4.0.1/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.2ms) (pid:1643)
ESC[0;37m2015-08-26 13:00:09.327ESC[0m [ESC[32mINFO ESC[0m] Rendered vendor/bundle/ruby/2.2.0/gems/exception_notification-4.0.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms) (pid:1643)
ESC[0;37m2015-08-26 13:00:09.328ESC[0m [ESC[32mINFO ESC[0m] Rendered vendor/bundle/ruby/2.2.0/gems/exception_notification-4.0.1/lib/exception_notifier/views/exception_notifier/_data.text.erb (0.2ms) (pid:1643)
ESC[0;37m2015-08-26 13:00:09.328ESC[0m [ESC[32mINFO ESC[0m] Rendered vendor/bundle/ruby/2.2.0/gems/exception_notification-4.0.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms) (pid:1643)
ESC[0;37m2015-08-26 13:00:09.329ESC[0m [ESC[32mINFO ESC[0m] Rendered vendor/bundle/ruby/2.2.0/gems/exception_notification-4.0.1/lib/exception_notifier/views/exception_notifier/background_exception_notification.text.erb (3.6ms) (pid:1643)
ESC[0;37m2015-08-26 13:00:09.726ESC[0m [ESC[32mINFO ESC[0m] Sent mail to erik@belnet.be, philippe@belnet.be (394.7ms) (pid:1643)
ESC[0;37m2015-08-26 13:00:09.728ESC[0m [ESC[32mINFO ESC[0m] Rendered errors/error_500.html.haml within layouts/error (0.7ms) (pid:1643)
ESC[0;37m2015-08-26 13:00:09.747ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_application_navbar.html.haml (15.3ms) (pid:1643)
ESC[0;37m2015-08-26 13:00:09.748ESC[0m [ESC[32mINFO ESC[0m] Rendered errors/_default_content.html.haml (0.5ms) (pid:1643)
ESC[0;37m2015-08-26 13:00:09.749ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_footer_simple.html.haml (1.3ms) (pid:1643)
ESC[0;37m2015-08-26 13:00:09.750ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_analytics.html.haml (0.1ms) (pid:1643)
ESC[0;37m2015-08-26 13:00:09.750ESC[0m [ESC[32mINFO ESC[0m] Rendered layouts/_notifications.html.haml (0.2ms) (pid:1643)
ESC[0;37m2015-08-26 13:00:09.751ESC[0m [ESC[32mINFO ESC[0m] Completed 500 Internal Server Error in 454ms (Views: 24.1ms | ActiveRecord: 2.3ms) (pid:1643)
