### ISSUE TITLE
An AbstractController::DoubleRenderError occurred in spaces#index

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#807]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1845, http://dev.mconf.org/redmine/issues/1845
Original Date: 2015-10-29
Original Assignee: Lucas Zawacki

---

This error happened in production a few times already.

```
This error happened in production a few times already.

```
Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".
  app/controllers/application_controller.rb:200:in `render_error_page'

-------------------------------
Request:
-------------------------------

  * URL        : https://any-server/spaces
  * HTTP Method: GET
  * IP address : 178.xxx.xxx.xx
  * Parameters : {"action"=>"index", "controller"=>"spaces"}
  * Timestamp  : 2015-10-05 08:46:58 -0300
  * Server : xxxxxx
  * Rails root : /var/www/mconf-web/releases/20150918231756
  * Process: 23848

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: #<ActionDispatch::Request::Session:0x7f73060c0708 not yet loaded>

-------------------------------
Environment:
-------------------------------

  * DOCUMENT_ROOT                                  : /var/www/mconf-web/current/public
  * HTTPS                                          : on
  * HTTP_ACCEPT                                    : */*
  * HTTP_ACCEPT_ENCODING                           : gzip, deflate, identity
  * HTTP_CONNECTION                                : Close
  * HTTP_DATE                                      : Mon, 5 Oct 2015 11:46:56 GMT
  * HTTP_FROM                                      : crawler@exabot.com
  * HTTP_HOST                                      : any-server
  * HTTP_USER_AGENT                                : Mozilla/5.0 (compatible; Exabot/3.0; +http://www.exabot.com/go/robot)
  * ORIGINAL_FULLPATH                              : /spaces
  * ORIGINAL_SCRIPT_NAME                           :
  * PASSENGER_APP_GROUP_NAME                       : /var/www/mconf-web/current
  * PASSENGER_APP_ROOT                             : /var/www/mconf-web/current
  * PASSENGER_APP_TYPE                             : rack
  * PASSENGER_CONNECT_PASSWORD                     : [FILTERED]
  * PASSENGER_DEBUGGER                             : false
  * PASSENGER_FRIENDLY_ERROR_PAGES                 : true
  * PASSENGER_MAX_PRELOADER_IDLE_TIME              : -1
  * PASSENGER_RESTART_DIR                          :
  * PASSENGER_RUBY                                 : /usr/local/rbenv/versions/2.2.0/bin/ruby
  * PASSENGER_SHOW_VERSION_IN_HEADER               : true
  * PASSENGER_SPAWN_METHOD                         : smart
  * PASSENGER_STATUS_LINE                          : false
  * PASSENGER_STAT_THROTTLE_RATE                   : 0
  * PATH_INFO                                      : /spaces
  * QUERY_STRING                                   :
  * REMOTE_ADDR                                    : 178.xxx.xxx.xx
  * REMOTE_PORT                                    : 33756
  * REQUEST_METHOD                                 : GET
  * REQUEST_URI                                    : /spaces
  * ROUTES_70065972820240_SCRIPT_NAME              :
  * ROUTES_70065973812920_SCRIPT_NAME              :
  * SCRIPT_NAME                                    :
  * SCRIPT_URI                                     : https://any-server/spaces
  * SCRIPT_URL                                     : /spaces
  * SERVER_ADDR                                    : 200.xxx.xx.xx
  * SERVER_ADMIN                                   : [no address given]
  * SERVER_NAME                                    : any-server
  * SERVER_PORT                                    : 443
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : Apache
  * action_controller.instance                     : #<SpacesController:0x007f73060bca68>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x007f730024dbd0>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x007f73060b5308>
  * action_dispatch.cookies_serializer             :
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x007f7300254bd8>
  * action_dispatch.logger                         : #<ActiveSupport::Logger:0x007f7302997420>
  * action_dispatch.parameter_filter               : [:password, :password_confirmation]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 178.xxx.xxx.xx
  * action_dispatch.request.accepts                : [#<Mime::Type:0x007f73060b6d70 @synonyms=[], @symbol=nil, @string="*/*">]
  * action_dispatch.request.content_type           :
  * action_dispatch.request.formats                : [#<Mime::Type:0x007f73060b6d70 @synonyms=[], @symbol=nil, @string="*/*">]
  * action_dispatch.request.parameters             : {"action"=>"index", "controller"=>"spaces"}
  * action_dispatch.request.path_parameters        : {:action=>"index", :controller=>"spaces"}
  * action_dispatch.request.query_parameters       : {}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {}
  * action_dispatch.request_id                     : ****
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x007f7302d77220>
  * action_dispatch.secret_key_base                : ****
  * action_dispatch.secret_token                   : ****
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : signed cookie
  * rack.errors                                    : #<IO:0x007f72ffa7d540>
  * rack.hijack                                    : #<Proc:0x007f73060c33e0@/usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/rack/thread_handler_extension.rb:69 (lambda)>
  * rack.hijack?                                   : true
  * rack.input                                     : #<PhusionPassenger::Utils::TeeInput:0x007f73060c3868>
  * rack.multiprocess                              : true
  * rack.multithread                               : false
  * rack.request.cookie_hash                       : {}
  * rack.request.query_hash                        : {}
  * rack.request.query_string                      :
  * rack.run_once                                  : false
  * rack.session                                   : #<ActionDispatch::Request::Session:0x007f73060c0708>
  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x007f73060c05c8>
  * rack.url_scheme                                : https
  * rack.version                                   : [1, 2]
  * warden                                         : Warden::Proxy:70065999707860 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:ldap_authenticatable, :rememberable, :database_authenticatable]}, :intercept_401=>false, :failure_app=>CustomFailedLoginRedirection}

-------------------------------
Backtrace:
-------------------------------

  app/controllers/application_controller.rb:200:in `render_error_page'
  app/controllers/application_controller.rb:217:in `render_500'

```

```

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2015-10-29T14:02:14Z

---

A very similar error has been happening in background:

```
An AbstractController::DoubleRenderError occurred in background at 2015-10-18 18:15:27 -0200 

 Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/rendering.rb:15:in `render'

  -------------------------------
Backtrace:
-------------------------------

  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/rendering.rb:15:in `render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /usr/local/rbenv/versions/2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/core_ext/benchmark.rb:12:in `ms'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:40:in `render'
  /var/www/mconf-web/releases/20150918231756/app/controllers/application_controller.rb:200:in `render_error_page'
  /var/www/mconf-web/releases/20150918231756/app/controllers/application_controller.rb:217:in `render_500'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/rescuable.rb:80:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/rescuable.rb:80:in `rescue_with_handler'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/rescue.rb:15:in `rescue_with_handler'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/rescue.rb:32:in `rescue in process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:159:in `block in instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:159:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/abstract_controller/base.rb:136:in `process'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/rendering.rb:30:in `process'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal.rb:196:in `dispatch'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal.rb:232:in `block in action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:82:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:50:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/journey/router.rb:71:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/journey/router.rb:59:in `each'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/journey/router.rb:59:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:678:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/exception_notification-4.0.1/lib/exception_notification/rack.rb:28:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/flash.rb:254:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/query_cache.rb:36:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:82:in `run_callbacks'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/rack/logger.rb:38:in `call_app'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/rack/logger.rb:20:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/tagged_logging.rb:26:in `tagged'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/tagged_logging.rb:68:in `tagged'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/rack/logger.rb:20:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/engine.rb:514:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/application.rb:144:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/railtie.rb:194:in `public_send'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/railtie.rb:194:in `method_missing'
  /usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

-------------------------------
Data:
-------------------------------

  * data: {}

```

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Lucas Zawacki** (Lucas Zawacki)
Original Date: 2015-12-01T19:40:28Z

---

https://github.com/mconf/mconf-web/pull/166

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2015-12-15T16:52:26Z

---

Considering it resolved. Will reopen if we see this again.
