### ISSUE TITLE
undefined method `find_by_id_with_disabled'

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#816]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1872, http://dev.mconf.org/redmine/issues/1872

Original Assignee: Lucas Zawacki

---

Triggered at  @/var/www/mconf-web/releases/20150918231756/app/views/private_messages/_show_sent.html.haml:25@.

Full error stack:

```
A NoMethodError occurred in background at 2015-11-25 08:01:40 -0200 :

  undefined method `find_by_id_with_disabled' for #<Class:0x007f42472457f8>
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/dynamic_matchers.rb:26:in `method_missing'

  -------------------------------
Backtrace:
-------------------------------

  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
  /var/www/mconf-web/releases/20150918231756/app/views/private_messages/_show_sent.html.haml:25:in `_app_views_private_messages__show_sent_html_haml__2883823681240845917_69961274442720'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/template.rb:145:in `block in render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:161:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/template.rb:339:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/template.rb:143:in `render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/renderer/partial_renderer.rb:279:in `block in render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:159:in `block in instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:159:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/renderer/partial_renderer.rb:278:in `render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/renderer/renderer.rb:47:in `render_partial'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/renderer/renderer.rb:21:in `render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/helpers/rendering_helper.rb:32:in `render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/haml-4.0.5/lib/haml/helpers/action_view_mods.rb:10:in `block in render_with_haml'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/haml-4.0.5/lib/haml/helpers.rb:89:in `non_haml'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/haml-4.0.5/lib/haml/helpers/action_view_mods.rb:10:in `render_with_haml'
  /var/www/mconf-web/releases/20150918231756/app/views/private_messages/show.html.haml:46:in `block in _app_views_private_messages_show_html_haml___1338328545413095565_69961293710000'
  /var/www/mconf-web/releases/20150918231756/app/views/private_messages/show.html.haml:43:in `each'
  /var/www/mconf-web/releases/20150918231756/app/views/private_messages/show.html.haml:43:in `_app_views_private_messages_show_html_haml___1338328545413095565_69961293710000'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/template.rb:145:in `block in render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:161:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/template.rb:339:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/template.rb:143:in `render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:159:in `block in instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:159:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/renderer/template_renderer.rb:53:in `render_template'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/renderer/template_renderer.rb:17:in `render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/renderer/renderer.rb:42:in `render_template'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/renderer/renderer.rb:23:in `render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/rendering.rb:99:in `_render_template'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/streaming.rb:217:in `_render_template'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/rendering.rb:82:in `render_to_body'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/renderers.rb:32:in `render_to_body'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/abstract_controller/rendering.rb:25:in `render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/rendering.rb:16:in `render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /usr/local/rbenv/versions/2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/core_ext/benchmark.rb:12:in `ms'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:40:in `render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/abstract_controller/base.rb:189:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/rendering.rb:10:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:113:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:113:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:229:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:229:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:86:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:86:in `run_callbacks'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:159:in `block in instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:159:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/abstract_controller/base.rb:136:in `process'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/rendering.rb:30:in `process'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal.rb:196:in `dispatch'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal.rb:232:in `block in action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:82:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:50:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/journey/router.rb:71:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/journey/router.rb:59:in `each'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/journey/router.rb:59:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:678:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/exception_notification-4.0.1/lib/exception_notification/rack.rb:28:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/flash.rb:254:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/query_cache.rb:36:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:82:in `run_callbacks'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/rack/logger.rb:38:in `call_app'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/rack/logger.rb:20:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/tagged_logging.rb:26:in `tagged'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/tagged_logging.rb:68:in `tagged'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/rack/logger.rb:20:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/engine.rb:514:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/application.rb:144:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/railtie.rb:194:in `public_send'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/railtie.rb:194:in `method_missing'
  /usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

-------------------------------
Data:
-------------------------------

  * data: {}

```

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Lucas Zawacki** (Lucas Zawacki)
Original Date: 2015-12-09T18:45:06Z

---

https://github.com/mconf/mconf-web/pull/167
