### ISSUE TITLE
undefined method `name' for nil:NilClass at app/models/join_request.rb:76:in `role'

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#817]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1873, http://dev.mconf.org/redmine/issues/1873

Original Assignee: Lucas Zawacki

---

Full error stack:

```
A NoMethodError occurred in background at 2015-11-26 17:49:32 -0200 :

  undefined method `name' for nil:NilClass
  /var/www/mconf-web/releases/20150918231756/app/models/join_request.rb:76:in `role'

  -------------------------------
Backtrace:
-------------------------------

  /var/www/mconf-web/releases/20150918231756/app/models/join_request.rb:76:in `role'
  /var/www/mconf-web/releases/20150918231756/app/models/join_request.rb:95:in `add_candidate_to_group'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:424:in `block in make_lambda'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:160:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:160:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:86:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:86:in `run_callbacks'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/callbacks.rb:302:in `create_or_update'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/persistence.rb:103:in `save'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/validations.rb:51:in `save'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/attribute_methods/dirty.rb:21:in `save'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/transactions.rb:268:in `block (2 levels) in save'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/transactions.rb:208:in `transaction'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/transactions.rb:268:in `block in save'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/transactions.rb:267:in `save'
  /var/www/mconf-web/releases/20150918231756/app/controllers/join_requests_controller.rb:151:in `block in save_for_accept_and_decline'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/mime_responds.rb:433:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/mime_responds.rb:433:in `retrieve_collector_from_mimes'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/mime_responds.rb:256:in `respond_to'
  /var/www/mconf-web/releases/20150918231756/app/controllers/join_requests_controller.rb:150:in `save_for_accept_and_decline'
  /var/www/mconf-web/releases/20150918231756/app/controllers/join_requests_controller.rb:107:in `accept'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/abstract_controller/base.rb:189:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/rendering.rb:10:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:113:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:113:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:149:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:149:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:149:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:215:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:229:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:229:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:166:in `block in halting'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:86:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:86:in `run_callbacks'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:159:in `block in instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/notifications.rb:159:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/abstract_controller/base.rb:136:in `process'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.4/lib/action_view/rendering.rb:30:in `process'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal.rb:196:in `dispatch'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_controller/metal.rb:232:in `block in action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:82:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:50:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/journey/router.rb:71:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/journey/router.rb:59:in `each'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/journey/router.rb:59:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/route_set.rb:678:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/exception_notification-4.0.1/lib/exception_notification/rack.rb:28:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:35:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/flash.rb:254:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/query_cache.rb:36:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/callbacks.rb:82:in `run_callbacks'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/rack/logger.rb:38:in `call_app'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/rack/logger.rb:20:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/tagged_logging.rb:26:in `tagged'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/tagged_logging.rb:68:in `tagged'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/rack/logger.rb:20:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/engine.rb:514:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/application.rb:144:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/railtie.rb:194:in `public_send'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/railtie.rb:194:in `method_missing'
  /usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

-------------------------------
Data:
-------------------------------

  * data: {}

```

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Lucas Zawacki** (Lucas Zawacki)
Original Date: 2015-12-18T22:46:37Z

---

https://github.com/mconf/mconf-web/pull/173

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2016-01-04T17:58:55Z

---

Considering it as solved. Will reopen if it happens again in production.
