### ISSUE TITLE
undefined method `[]' for nil:NilClass on ApplicationController#append_info_to_payload

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#824]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1890, http://dev.mconf.org/redmine/issues/1890

Original Assignee: Leonardo Daronco

---

```
A NoMethodError occurred in background at 2015-12-07 16:48:41 -0200 :

  undefined method `[]' for nil:NilClass
  /var/www/mconf-web/releases/20151201192846/app/controllers/application_controller.rb:215:in `append_info_to_payload'

  -------------------------------
Backtrace:
-------------------------------

  /var/www/mconf-web/releases/20151201192846/app/controllers/application_controller.rb:215:in `append_info_to_payload'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/metal/instrumentation.rb:36:in `block in process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/notifications.rb:159:in `block in instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/notifications.rb:159:in `instrument'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/abstract_controller/base.rb:136:in `process'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionview-4.1.11/lib/action_view/rendering.rb:30:in `process'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/metal.rb:196:in `dispatch'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_controller/metal.rb:232:in `block in action'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:82:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:50:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/journey/router.rb:73:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/journey/router.rb:59:in `each'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/journey/router.rb:59:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:692:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/exception_notification-4.0.1/lib/exception_notification/rack.rb:28:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/conditionalget.rb:25:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/flash.rb:254:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/cookies.rb:562:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/query_cache.rb:36:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/callbacks.rb:82:in `run_callbacks'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.11/lib/rails/rack/logger.rb:38:in `call_app'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.11/lib/rails/rack/logger.rb:20:in `block in call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/tagged_logging.rb:26:in `tagged'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/tagged_logging.rb:68:in `tagged'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.11/lib/rails/rack/logger.rb:20:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.11/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.11/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.11/lib/rails/engine.rb:514:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.11/lib/rails/application.rb:144:in `call'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.11/lib/rails/railtie.rb:194:in `public_send'
  /var/www/mconf-web/shared/bundle/ruby/2.2.0/gems/railties-4.1.11/lib/rails/railtie.rb:194:in `method_missing'
  /usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

-------------------------------
Data:
-------------------------------

  * data: {}

```

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2016-01-04T18:17:51Z

---

Another stack trace for the same error but triggered differently:

```
A NoMethodError occurred in custom_bigbluebutton_rooms#join:

  undefined method `[]' for nil:NilClass
  app/controllers/application_controller.rb:215:in `append_info_to_payload'


-------------------------------
Request:
-------------------------------

  * URL        : https://xxxxxxxxxxxx/bigbluebutton/rooms/mconf/join
  * HTTP Method: GET
  * IP address : xxx.xxx.xxx.xxx
  * Parameters : {"action"=>"join", "controller"=>"custom_bigbluebutton_rooms", "id"=>"mconf"}
  * Timestamp  : 2015-12-07 16:48:40 -0200
  * Server : lab-mconf-portal01
  * Rails root : /var/www/mconf-web/releases/20151201192846
  * Process: 1586

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: #<ActionDispatch::Request::Session:0x7f3b17664140 not yet loaded>

-------------------------------
Environment:
-------------------------------

  * DOCUMENT_ROOT                                  : /var/www/mconf-web/current/public
  * HTTPS                                          : on
  * HTTP_ACCEPT                                    : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  * HTTP_ACCEPT_ENCODING                           : gzip, deflate, sdch
  * HTTP_ACCEPT_LANGUAGE                           : it,en-US;q=0.8,en;q=0.6,pt;q=0.4
  * HTTP_CONNECTION                                : keep-alive
  * HTTP_COOKIE                                    : _saml_idp=aHR0cHM6Ly9sb2dpbi51ZnJncy5ici9pZHAvc2hpYmJvbGV0aA%3D%3D; __utma=105344415.44102139.1417183019.1446827749.1447178418.39; __utmc=105344415; __utmz=105344415.1433345942.26.5.utmcsr=lab.mconf-live.rnp.br|utmccn=(referral)|utmcmd=referral|utmcct=/conference/; _shibsession_64656661756c7468747470733a2f2f6c61622e6d636f6e662e726e702e62722f73686962626f6c6574682d737032=_0d79b8827db81385c3e288ced8b0c776; __utma=230281473.446479364.1418408561.1446832889.1449504056.38; __utmc=230281473; __utmz=230281473.1446743266.36.2.utmcsr=login.ufrgs.br|utmccn=(referral)|utmcmd=referral|utmcct=/idp/profile/SAML2/Redirect/SSO; _gat=1; _ga=GA1.2.446479364.1418408561
  * HTTP_HOST                                      : xxxxxxx
  * HTTP_REFERER                                   : xxxxxxxxx/spaces/mconf
  * HTTP_UPGRADE_INSECURE_REQUESTS                 : 1
  * HTTP_USER_AGENT                                : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36
  * ORIGINAL_FULLPATH                              : /bigbluebutton/rooms/mconf/join
  * ORIGINAL_SCRIPT_NAME                           :
  * PASSENGER_APP_GROUP_NAME                       : /var/www/mconf-web/current
  * PASSENGER_APP_ROOT                             : /var/www/mconf-web/current
  * PASSENGER_APP_TYPE                             : rack
  * PASSENGER_CONNECT_PASSWORD                     : [FILTERED]
  * PASSENGER_DEBUGGER                             : false
  * PASSENGER_FRIENDLY_ERROR_PAGES                 : true
  * PASSENGER_MAX_PRELOADER_IDLE_TIME              : -1
  * PASSENGER_RESTART_DIR                          :
  * PASSENGER_RUBY                                 : /usr/local/rbenv/versions/2.2.0/bin/ruby
  * PASSENGER_SHOW_VERSION_IN_HEADER               : true
  * PASSENGER_SPAWN_METHOD                         : smart
  * PASSENGER_STATUS_LINE                          : false
  * PASSENGER_STAT_THROTTLE_RATE                   : 0
  * PATH_INFO                                      : /bigbluebutton/rooms/mconf/join
  * QUERY_STRING                                   :
  * REMOTE_ADDR                                    : 143.54.10.155
  * REMOTE_PORT                                    : 49313
  * REQUEST_METHOD                                 : GET
  * REQUEST_URI                                    : /bigbluebutton/rooms/mconf/join
  * ROUTES_69945860496860_SCRIPT_NAME              :
  * SCRIPT_NAME                                    :
  * SCRIPT_URI                                     : https://xxxxxxxxxx/bigbluebutton/rooms/mconf/join
  * SCRIPT_URL                                     : /bigbluebutton/rooms/mconf/join
  * SERVER_ADDR                                    : 200.130.99.176
  * SERVER_ADMIN                                   : [no address given]
  * SERVER_NAME                                    : xxxxxxxxxxxxx
  * SERVER_PORT                                    : 443
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : Apache
  * action_controller.instance                     : #<CustomBigbluebuttonRoomsController:0x007f3b17656158>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x007f3b115a9918>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x007f3b175e7438>
  * action_dispatch.cookies_serializer             :
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x007f3b115bca90>
  * action_dispatch.logger                         : #<ActiveSupport::Logger:0x007f3b141dab40>
  * action_dispatch.parameter_filter               : [:password, :password_confirmation]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 143.54.10.155
  * action_dispatch.request.content_type           :
  * action_dispatch.request.flash_hash             : #<ActionDispatch::Flash::FlashHash:0x007f3b175705b8>
  * action_dispatch.request.formats                : [#<Mime::Type:0x007f3b127d8ff8 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html">]
  * action_dispatch.request.parameters             : {"action"=>"join", "controller"=>"custom_bigbluebutton_rooms", "id"=>"mconf"}
  * action_dispatch.request.path_parameters        : {:action=>"join", :controller=>"custom_bigbluebutton_rooms", :id=>"mconf"}
  * action_dispatch.request.query_parameters       : {}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {}
  * action_dispatch.request_id                     : 5ebf9ae9-49e9-4a36-b502-3e99e43c4984
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x007f3b14563bb8>
  * action_dispatch.secret_key_base                : c4aa1f3569caa222d7434d1238a4ab7041e148f60333029dd0d90ae8b85c3411c015339d682d003d322730befd841655b863bb5193db088cf54215e72e8cf81e
  * action_dispatch.secret_token                   : 0b22a987a3beb701c128a787cd2914351df06cfce413ca0e4034574e0f7d144692d940fe02374c39dbbbc898e9bda27356a89d14d5c4235f4979b4bea0072f0b
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : signed cookie
  * rack.errors                                    : #<IO:0x007f3b10d15540>
  * rack.hijack                                    : #<Proc:0x007f3b176663f0@/usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-4.0.59/lib/phusion_passenger/rack/thread_handler_extension.rb:69 (lambda)>
  * rack.hijack?                                   : true
  * rack.input                                     : #<PhusionPassenger::Utils::TeeInput:0x007f3b17666620>
  * rack.multiprocess                              : true
  * rack.multithread                               : false
  * rack.request.cookie_hash                       : {"_saml_idp"=>"aHR0cHM6Ly9sb2dpbi51ZnJncy5ici9pZHAvc2hpYmJvbGV0aA==", "__utma"=>"105344415.44102139.1417183019.1446827749.1447178418.39", "__utmc"=>"105344415", "__utmz"=>"105344415.1433345942.26.5.utmcsr=lab.mconf-live.rnp.br|utmccn=(referral)|utmcmd=referral|utmcct=/conference/", "_shibsession_64656661756c7468747470733a2f2f6c61622e6d636f6e662e726e702e62722f73686962626f6c6574682d737032"=>"_0d79b8827db81385c3e288ced8b0c776", "_gat"=>"1", "_ga"=>"GA1.2.446479364.1418408561"}
  * rack.request.cookie_string                     : _saml_idp=aHR0cHM6Ly9sb2dpbi51ZnJncy5ici9pZHAvc2hpYmJvbGV0aA%3D%3D; __utma=105344415.44102139.1417183019.1446827749.1447178418.39; __utmc=105344415; __utmz=105344415.1433345942.26.5.utmcsr=lab.mconf-live.rnp.br|utmccn=(referral)|utmcmd=referral|utmcct=/conference/; _shibsession_64656661756c7468747470733a2f2f6c61622e6d636f6e662e726e702e62722f73686962626f6c6574682d737032=_0d79b8827db81385c3e288ced8b0c776; __utma=230281473.446479364.1418408561.1446832889.1449504056.38; __utmc=230281473; __utmz=230281473.1446743266.36.2.utmcsr=login.ufrgs.br|utmccn=(referral)|utmcmd=referral|utmcct=/idp/profile/SAML2/Redirect/SSO; _gat=1; _ga=GA1.2.446479364.1418408561
  * rack.request.query_hash                        : {}
  * rack.request.query_string                      :
  * rack.run_once                                  : false
  * rack.session                                   : #<ActionDispatch::Request::Session:0x007f3b17664140>
  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x007f3b176640f0>
  * rack.url_scheme                                : https
  * rack.version                                   : [1, 2]
  * warden                                         : Warden::Proxy:69945886179180 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:ldap_authenticatable, :rememberable, :database_authenticatable]}, :intercept_401=>false, :failure_app=>CustomFailedLoginRedirection}

-------------------------------
Backtrace:
-------------------------------

  app/controllers/application_controller.rb:215:in `append_info_to_payload'

```
